CREATE TABLE hiredate_history
(DEPARTMENT_ID	NUMBER(4),
HIREDATE	DATE)
/

CREATE TABLE hiredate_history_00
(DEPARTMENT_ID	NUMBER(4),
HIREDATE	DATE)
/


CREATE TABLE hiredate_history_99
(DEPARTMENT_ID	NUMBER(4),
HIREDATE	DATE)
/


CREATE table MGR_HISTORY
(EMPLOYEE_ID	NUMBER(6),
MANAGER_ID	NUMBER(6),
SALARY	NUMBER(8,2))
/


CREATE table SAL_HISTORY
(EMPLOYEE_ID	NUMBER(6),
HIRE_DATE	DATE,
SALARY	NUMBER(8,2))
/


CREATE TABLE SALES_SOURCE_DATA
(employee_id 	NUMBER(6),
WEEK_ID	NUMBER(2),
SALES_MON	NUMBER(8,2),
SALES_TUE	NUMBER(8,2),
SALES_WED	NUMBER(8,2),
SALES_THUR	NUMBER(8,2),
SALES_FRI	NUMBER(8,2))
/
INSERT INTO SALES_SOURCE_DATA VALUES
(178, 6, 1750,2200,1500,1500,3000)
/
commit
/


CREATE table SPECIAL_SAL
(EMPLOYEE_ID	NUMBER(6),
SALARY	NUMBER(8,2))
/

CREATE TABLE SALES_INFO
(employee_id 	NUMBER(6),
WEEK	NUMBER(2),
SALES	NUMBER(8,2))
/